### PR TITLE
Compatibility with Hyper 2.0.0

### PR DESCRIPTION
**Pull request by WickedSik**
@webmatze Minor changes, but this makes it work!

### CODE REVIEW

**Comment by Xapphire13** [comment]
Looks awesome! Nice to see it can be fixed with very little change. I assume this will probably be backward compatible with hyper 1 also =]

**Comment by WickedSik** [comment]
Honestly, I have no idea if this is backwards compatible. But, I suppose that expanding the selectors that use `:global()` should keep backwards compatibility. I.e. `:global(html), html {`

**Comment by webmatze** [comment]
Cool. This works for version 2 of hyper.
Unfortunately, it does not work with the older versions. :(

I was working on a fix that is backward compatible. See #45 

But thanks for the great afford. Will keep this for later changes when we do not need to support older versions anymore.

**Comment by WickedSik** [comment]
No problem, nice to see you fixed it in a better way ^^

**Pull request closed without merging**
