### PR TITLE
add css overflow to #hyperborder .hyper_main

### PR DESCRIPTION
**Pull request by zgobolos**

### CODE REVIEW

**Comment by zgobolos** [comment]
.

**Comment by webmatze** [comment]
Hi @zgobolos thank you for your contribution. 
Can you provide a short description of what your change fixes?

**Comment by zgobolos** [comment]
Hi @webmatze, the patch applies to the inner border. The problem it solves is the content of the inner border can overflow, eg. https://github.com/henrikruscon/hyper-statusline has a rectangle shape where its bottom left and bottom right corners cover the stroke area between the inner and outer border.

The patch prevents inner content to overflow the border stroke area.

**Comment by webmatze** [comment]
Thank you. I testet it with **hyper-statusline** and it works. I will create a release soon.

**Pull request merged**
